# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 10143
  start_block: 0
  contracts:
  - name: PairFactory
    address:
    - 0x22595aA7f5298b49D62450DA6300882Fb3d98eBc
    handler: src/EventHandlers.ts
    events:
    - event: PairCreated(address indexed token0, address indexed token1, bool stable, address pair, uint256 )
  - name: RewardsDistributor
    address:
    - 0x38Fd3f88a46239D8CEcB768f8E7620d861D2DE13
    handler: src/EventHandlers.ts
    events:
    - event: CheckpointToken(uint256 time, uint256 tokens)
    - event: Claimed(uint256 tokenId, uint256 amount, uint256 claim_epoch, uint256 max_epoch)
unordered_multichain_mode: true
